name: 'Destroy Infrastructure using Terraform'

on:
 workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_AUTH }}
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: ./infra/main

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: | 
        terraform init

    # destroy
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
